---
codecov:
  branch: python
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        threshold: 1%
    patch:
      default:
        enabled: yes
        threshold: 1%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

ignore:
  - "libs"
