############ compiler settings
CC=/usr/lib/lam/bin/hcc
CFLAGS=-g -O3 -Wall -march=i586 -fschedule-insns -fschedule-insns2 \
         -frerun-cse-after-loop -ffast-math
CFLAGS+= -I/usr/lib/lam/include
DEPEND=makedepend

CXX=g++
CXXFLAGS=$(CFLAGS) -felide-constructors -fomit-frame-pointer -fno-rtti

############ linker settings
LINK=$(CC)
# tcl libraries
LDLIBS=  -ltcl8.3
# mpi libraries
LDLIBS+=