#!/bin/bash

espresso=../../build/pypresso
client_script=lj_gibbs_client.py
output_base=lj_gibbs
port=10000

if [[ ! -e $espresso ]]
then
    echo Invalid path to pypresso script: $espresso
  exit 1
fi

if [[ ! -s $client_script ]]
then
  echo Client script not found: $client_script
  exit 1
fi


for kT in $*
do
  for seed in 1 2 3 4 5 6 7 8
  do
    output_name=${output_base}-kT-$kT-seed-$seed
    $espresso gibbs_ensemble_socket.py -C $client_script --seed $seed -P $port -T $kT --steps 80000 --output-file ${output_name}.pkl & 
    let port=$port+1
  done
done
wait
