from enum import IntFlag


class Propagation(IntFlag):
    NONE = 0
    TRANS_SYSTEM_DEFAULT = 1
    TRANS_LANGEVIN = 2
    TRANS_LANGEVIN_NPT = 4
    TRANS_VS_RELATIVE = 8
    TRANS_LB_MOMENTUM_EXCHANGE = 16
    TRANS_LB_TRACER = 32
    TRANS_BROWNIAN = 64
    TRANS_STOKESIAN = 128
    ROT_LANGEVIN = 256
    ROT_VS_RELATIVE = 512
    ROT_BROWNIAN = 1024
