#
# Copyright (C) 2020-2026 The ESPResSo project
#
# This file is part of ESPResSo.
#
# ESPResSo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ESPResSo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import json
import pathlib

import lxml.etree
import jupyter_core.paths
import nbconvert


class NotebookLinksValidator():
    """
    Check that links in Jupyter Notebooks pointing to resources generated by
    the ESPResSo project are valid, i.e. the target HTML files exist and
    HTML anchors exist. This includes links to sections of the notebook
    (table of contents, bibliography, etc.) and links to the Sphinx user guide.

    Parameters
    ----------
    build_root: :obj:`str`
        Path to the ESPResSo build directory. The Sphinx files will be
        searched in :file:`doc/sphinx/html`.
    html_exporter: :obj:`nbformat.HTMLExporter`
        Custom NB convert HTML exporter.

    """

    def __init__(self, build_root='.', html_exporter=None):
        if html_exporter is None:
            html_exporter = self.make_default_html_exporter()
        html_exporter.template_name = "classic"
        self.html_exporter = html_exporter
        self.sphinx_docs_cache = {}
        root = pathlib.Path(build_root)
        self.sphinx_html_root = root / "doc" / "sphinx" / "html"
        assert self.sphinx_html_root.exists()

    @classmethod
    def make_default_html_exporter(cls):
        """
        Create an HTML exporter based on the user's Jupyter settings.
        """
        exporter_kwargs = {}
        for path in jupyter_core.paths.jupyter_config_path():
            filepath = pathlib.Path(path) / "jupyter_nbconvert_config.json"
            if filepath.is_file():
                with open(filepath) as f:
                    config = json.load(f)
                exporter_kwargs = config.get("HTMLExporter", {})
                break
        return nbconvert.HTMLExporter(**exporter_kwargs)

    def validate(self, nb):
        """
        Parse a Jupyter Notebook and verify all links to local resources.

        Parameters
        ----------
        nb: :obj:`nbformat.notebooknode.NotebookNode`
            Jupyter notebook to process.

        Returns
        -------
        :obj:`list`
            List of warnings formatted as strings.
        """
        # convert notebooks to HTML
        html_string = self.html_exporter.from_notebook_node(nb)[0]
        # parse HTML
        html_parser = lxml.etree.HTMLParser()
        root = lxml.etree.fromstring(html_string, parser=html_parser)
        # process all links
        espressomd_website_root = 'https://espressomd.github.io/doc/'
        broken_links = []
        for link in root.xpath('//a'):
            url = link.attrib.get('href', '')
            if url.startswith(espressomd_website_root):
                # extract anchor
                anchor = None
                if '#' in url:
                    url, anchor = url.split('#', 1)
                # strip query
                if '?' in url:
                    url = url.split('?', 1)[0]
                # check file exists
                basename = url.split(espressomd_website_root, 1)[1]
                filepath = self.sphinx_html_root / basename
                if not filepath.is_file():
                    broken_links.append(f'"{url}" does not exist')
                    continue
                # check anchor exists
                if anchor is not None:
                    if filepath not in self.sphinx_docs_cache:
                        self.sphinx_docs_cache[filepath] = lxml.etree.parse(
                            str(filepath), parser=html_parser)
                    doc = self.sphinx_docs_cache[filepath]
                    nodes = doc.xpath(f'//*[@id="{anchor}"]')
                    if not nodes:
                        broken_links.append(
                            f'"{url}" has no anchor "{anchor}"')
            elif url.startswith('#'):
                # check anchor exists
                anchor = url[1:]
                nodes = root.xpath(f'//*[@id="{anchor}"]')
                if not nodes:
                    broken_links.append(f'notebook has no anchor "{anchor}"')
            elif url.startswith('file:///'):
                broken_links.append(
                    f'"{url}" is an absolute path to a local file')
        for link in root.xpath('//script'):
            url = link.attrib.get('src', '')
            if url.startswith('file:///'):
                broken_links.append(
                    f'"{url}" is an absolute path to a local file')
        return broken_links
