#!/bin/sh
# Copyright (C) 2010,2011,2014 The ESPResSo project
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
if test -n "$PYTHONPATH"; then
    PYTHONPATH=$PYTHONPATH:/home/itvgi/PHD/CODE/20150205_ESPResSo_TPB/espresso-1
else
    PYTHONPATH=/home/itvgi/PHD/CODE/20150205_ESPResSo_TPB/espresso-1
fi
export PYTHONPATH
exec /usr/bin/python $@
