#
# Copyright (C) 2013-2026 The ESPResSo project
# Copyright (C) 2012 Olaf Lenz
#
# This file is part of ESPResSo.
#
# ESPResSo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ESPResSo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import string
import inspect
import sys
import re
import os
# find featuredefs.py
moduledir = os.path.dirname(inspect.getfile(inspect.currentframe()))
sys.path.append(os.path.join(moduledir, '..'))
import featuredefs

if len(sys.argv) != 5:
    raise ValueError(
        f"Usage: {sys.argv[0]} DEFFILE HPPFILE IMPLHPPFILE MYCONFIGFILE")

path_def, path_hpp, path_impl_hpp, path_myconfig = sys.argv[1:6]
assert path_myconfig.endswith(".hpp.in")

print(f"Reading definitions from {path_def}")
defs = featuredefs.defs(path_def)


def add_define_prefix(m):
    feature = m.group(1)
    if feature in defs.allfeatures:
        return f"ESPRESSO_{feature}"
    return feature


with open(path_myconfig) as f:
    myconfig = f.read()

myconfig = re.sub("(?<![a-zA-Z0-9_])([A-Z0-9_]+)(?![a-zA-Z0-9_])",
                  add_define_prefix, f" {myconfig} ")[1:-1]

with open(path_myconfig.rsplit(".", 1)[0], "w") as f:
    f.write(myconfig)


disclaimer = f"""/*
 * WARNING: This file was generated automatically.
 * Do not modify it or your changes will be overwritten!
 * Modify features.def instead.
 */
"""

print(f"Writing {path_hpp}")
hfile = open(path_hpp, 'w')
hfile.write(disclaimer)
hfile.write("""
#pragma once
""")

hfile.write("""
/*********************************/
/* Handle definitions from CMake */
/*********************************/

#include "config/cmake_config.hpp"

// rename external features
""")

external_template = string.Template("""
#if defined(ESPRESSO_BUILD_WITH_$feature)
#undef ESPRESSO_BUILD_WITH_$feature
#define ESPRESSO_$feature
#endif
""")
for feature in sorted(defs.externals):
    hfile.write(external_template.substitute(feature=feature))

hfile.write("""
/************************************/
/* Handle definitions from MyConfig */
/************************************/

#include "config/myconfig-final.hpp"

""")

# handle implications
hfile.write("""\
/***********************/
/* Handle implications */
/***********************/
""")
for rules in defs.implications_topologically_ordered:
    for implied in sorted(rules.keys()):
        implying = sorted(rules[implied])
        condition = " || ".join(f"defined(ESPRESSO_{s})" for s in implying)
        if len(implying) > 1:
            condition = f"({condition})"
        hfile.write(
            f"#if !defined(ESPRESSO_{implied}) && {condition}\n"
            f"#define ESPRESSO_{implied}\n"
            f"#endif\n\n"
        )

# output warnings if internal features are set manually
hfile.write("""\
/*****************************************************/
/* Warn when derived switches are specified manually */
/*****************************************************/
""")
derivation_template = string.Template("""
// $feature equals $expr
#ifdef ESPRESSO_$feature
#warning "$feature is a derived switch and should not be set manually!"
#elif $cppexpr
#define ESPRESSO_$feature
#endif
""")
for feature, expr, cppexpr in sorted(defs.derivations):
    hfile.write(derivation_template.substitute(
        feature=feature, cppexpr=cppexpr, expr=expr))
hfile.write("\n")

# generate compiler errors when incompatible features are selected
hfile.write("""\
/***********************/
/* Handle requirements */
/***********************/
""")
requirement_string = """
// {feature} requires {expr}
#if defined(ESPRESSO_{feature}) && !({cppexpr})
#error "Feature {feature} requires {expr}"
#endif
"""
for feature, expr, cppexpr in sorted(defs.requirements):
    hfile.write(requirement_string.format(
        feature=feature, cppexpr=cppexpr, expr=expr))

hfile.close()

print(f"Writing {path_impl_hpp}")
cfile = open(path_impl_hpp, "w")

cfile.write(disclaimer)
cfile.write(f"""
#include "config/config-features.hpp"
#include "config/config.hpp"

/***********************/
/* Handle requirements */
/***********************/
""")

cfile.write("""
/****************/
/* Feature list */
/****************/

inline constexpr char const *const FEATURES[] = {
""")

feature_string = """
#ifdef ESPRESSO_{feature}
  "{feature}",
#endif
"""

for feature in sorted(defs.externals.union(defs.features, defs.derived)):
    cfile.write(feature_string.format(feature=feature))

cfile.write("""
  // zero-length arrays are not allowed by the C standard
  "__sentinel"

};
inline constexpr auto const NUM_FEATURES = sizeof(FEATURES) / sizeof(char*) - 1ul;
""")

cfile.write("""
/*********************/
/* Feature full list */
/*********************/

inline constexpr char const *const FEATURES_ALL[] = {\
""")

feature_string = """
  "{feature}","""

for feature in sorted(defs.allfeatures):
    cfile.write(feature_string.format(feature=feature))

cfile.write("""
};
inline constexpr auto const NUM_FEATURES_ALL = sizeof(FEATURES_ALL) / sizeof(char*);
""")

cfile.close()
