proc writepsf {file} {
    set f [open $file "w"]
    puts $f "PSF"
    puts $f [format "%8d !NATOM" [part number]]
    # write atoms and create bondlist
    set cnt 1
    set mp [setmd maxpart]
    set bondlist {}
    set bondcnt 0
    for {set p 0} { $p <= $mp } { incr p } {
	set tp [part $p p t]
	if { $tp != "na" } {
	    puts $f [format "%8d T%03d %4d UNX  FE   FE" \
			 $cnt $tp $p]
	    set count($p) $cnt
	    set bonds [part $p p b]
	    foreach b $bonds {
		set b [lindex $b 0]
		if {[llength $b ] == 2} {
		    incr bondcnt; lappend bondlist "{$cnt [lindex $b 1]}"
		}
	    }
	}
	incr cnt
    }
    #  write bonds
    puts $f [format "%8d !NBOND" $bondcnt]
    set bondlinecnt 0
    foreach b $bondlist {
	set b [lindex $b 0]
	if {[llength $b] == 2} {
	    incr bondcnt
	    eval "set p1 [lindex $b 0]"
	    eval "set p2 \$count([lindex $b 1])"
	    puts -nonewline $f [format "%8d%8d" $p1 $p2]
	    incr bondlinecnt
	    if {$bondlinecnt == 4} {
		puts $f ""
		set bondlinecnt 0
	    }
	}
    }
    close $f
}

proc writepdb {file} {
    set f [open $file "w"]
    puts $f "REMARK generated by tcl_md"
    # write atoms
    set mp [setmd maxpart]
    set cnt 0
    for {set p 0} { $p <= $mp } { incr p } {
	set tp [part $p p t]
	if { $tp != "na" } {
	    set pos [part $p p p]
	    puts $f [format "ATOM %6d  FE  UNX F%4d    %8.3f%8.3f%8.3f  0.00  0.00      T%03d" \
			 $cnt [expr $p % 10000] [lindex $pos 0] [lindex $pos 1] [lindex $pos 2] $tp]
	    incr cnt
	}
    }
    close $f
}
