function(UNIT_TEST)
    cmake_parse_arguments(TEST "" "NAME" "SRC;DEPENDS" ${ARGN})
    add_executable(${TEST_NAME} ${TEST_SRC})
    target_link_libraries(${TEST_NAME} PRIVATE Boost::unit_test_framework)
    if(TEST_DEPENDS)
        target_link_libraries(${TEST_NAME} PRIVATE ${TEST_DEPENDS})
    endif(TEST_DEPENDS)
    add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
endfunction(UNIT_TEST)